# Use uma imagem base do Python
FROM ubuntu:22.04

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo de requisitos e instale as dependências
COPY . .

RUN apt-get update && \
    apt-get install -y python3.11 && \
    apt-get install -y python3-pip

RUN pip install -r requirements.txt

# Comando padrão para rodar o script principal (ajuste conforme necessário)
ENTRYPOINT ["python3", "run.py"]
